services:

    # netshoot:
    #     image: nicolaka/netshoot:latest
    #     container_name: netshoot
    #     command: sleep infinity
    #     networks: 
    #         - shared-network
    
    gitlab:
        image: gitlab/gitlab-ce:18.6.6-ce.0
        container_name: gitlab
        restart: always
        hostname: '${GITLAB_HOSTNAME}'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                # Add any other gitlab.rb configuration here, each on its own line
                external_url '${GITLAB_EXTERNAL_URL}'
                nginx['listen_port'] = 80
        ports:
            - '80:80'
            - '443:443'
            - '22:22'
        volumes:
            - '$GITLAB_HOME/config:/etc/gitlab'
            - '$GITLAB_HOME/logs:/var/log/gitlab'
            - '$GITLAB_HOME/data:/var/opt/gitlab'
        shm_size: '256m'
        networks: 
            - shared-network

    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner1
        restart: always
        volumes: 
            - $GITLAB_RUNNER_HOME/config:/etc/gitlab-runner
            # [REQUIRED]: Socket do Docker Engine, responsável por fazer a comunicação com o Docker Engine (esse volume faz com que esse container consiga controlar o docker externo)
            - /var/run/docker.sock:/var/run/docker.sock   
        networks: 
            - shared-network

    backstage-app:
        build:
            dockerfile:	./Dockerfile
            context: ./BACKSTAGE APPS/backstage-app
        image: backstage-demo-fk:latest
        container_name: backstage-app
        ports:
            - "7007:7007"
        environment:
            # Default
            - APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment=true
            - BACKSTAGE_ENV=dev
            # Microsoft Auth
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            # Gilab
            - GITLAB_TOKEN=${GITLAB_TOKEN}
            - GITLAB_HOSTNAME=${GITLAB_HOSTNAME}
            - GITLAB_EXTERNAL_URL=${GITLAB_EXTERNAL_URL}
        # volumes:
        #     - backstage-volume:/app                     
        networks: 
            - shared-network
   
   
# NETWORK - CUSTOM
networks:
    shared-network:
        driver: bridge

